FROM node:15 as builder
ENV REACT_APP_ENV=development
WORKDIR /app 

COPY package.json ./
COPY package-lock.json ./
RUN npm install -production

COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html

