FROM node:15 as builder
ENV NODE_ENV=development
WORKDIR /app 

COPY package.json ./
COPY package-lock.json ./
RUN npm install -i

COPY . .
RUN npm run build-dev

FROM nginx:stable-alpine
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

