version: '3'

services:
  api:
    container_name: api
    build:
      context: ./API
      dockerfile: Dockerfile-development
    ports:
      - "5000:5000"
    depends_on:
      - prometheus
      - grafana
    networks: 
      - local

  frontend:
    container_name: frontend-development
    build:
      context: ./Frontend
      dockerfile: Dockerfile-development
    ports:
      - "3000:80"
    depends_on: 
      - api
      - grafana
      - prometheus
    networks: 
      - local

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus-development.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - local

  grafana:
    image: grafana/grafana:4.5.2
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - local

networks: 
  local:

volumes:
  grafana-storage:
