version: '3.4'

services:
  sim-api:
    container_name: sim-api
    labels: "prometheus-job=sim-api" # prometheus only scrapes services with label prometheus-job prefix.
    image: index.docker.io/minitwit/simulator_develop
    ports: 
      - "5001:5001"
    networks:
      - local
    deploy:
      replicas: 2 
      update_config:
        parallelism: 1
        delay: 20s
        order: start-first
      
  api:
    container_name: api
    image: index.docker.io/minitwit/api_develop
    ports:
      - "5000:5000"
    depends_on:
      - prometheus
      - grafana
    networks: 
      - local
    deploy:
      replicas: 2 
      update_config:
        parallelism: 1
        delay: 20s
        order: start-first

  frontend:
    container_name: frontend
    image: index.docker.io/minitwit/frontend_develop
    ports:
      - "3000:80"
    depends_on: 
      - api
      - grafana
      - prometheus
    networks: 
      - local
    deploy:
      replicas: 2 
      update_config:
        parallelism: 1
        delay: 20s
        order: start-first

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - local

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=devops21
      - GF_SECURITY_ADMIN_PASSWORD=-lEtMEIn-
    ports:
      - "3001:3000"
    user: "104"
    networks:
      - local
      - loki

  loki:
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
      - local

  promtail:
    image: grafana/promtail:2.0.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

networks:
  local:
    driver: overlay
    attachable: true
  loki:

volumes:
  grafana-storage:
