version: '3'
services:
  sim-api:
    container_name: sim-api
    image: index.docker.io/minitwit/simulator
    ports: 
      - "5001:5001"
      
  api:
    container_name: api
    image: index.docker.io/minitwit/api
    ports:
      - "5000:5000"
    networks: 
      - local

  frontend:
    container_name: frontend
    image: index.docker.io/minitwit/frontend
    ports:
      - "3000:80"
    depends_on: 
      - api
    networks: 
      - local

  watchtower:
    image: v2tec/whatchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/snap/docker/796/.docker/config.json:/config.json
    command: --interval 30

networks: 
  local:
