version: '3'

services:
  sim-api:
    container_name: sim-api
    image: index.docker.io/minitwit/simulator
    ports: 
      - "5001:5001"
    networks:
      - local
      
  api:
    container_name: api
    image: index.docker.io/minitwit/api
    ports:
      - "5000:5000"
    depends_on:
      - prometheus
      - grafana
    networks: 
      - local

  frontend:
    container_name: frontend
    image: index.docker.io/minitwit/frontend
    ports:
      - "3000:80"
    depends_on: 
      - api
      - grafana
      - prometheus
    networks: 
      - local

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/snap/docker/796/.docker/config.json:/config.json
    command: --interval 30

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - local


  grafana:
    image: grafana/grafana:4.5.2
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=devops21
      - GF_SECURITY_ADMIN_PASSWORD=-lEtMEIn-
    ports:
      - "3001:3000"
    networks:
      - local

networks: 
  local:

volumes:
  grafana-storage:
