version: '3'
services:
  sim-api:
    image: nieb/sim-api
    ports: 
      - "5001:5001"
      
  api:
    image: nieb/api
    ports:
      - "5000:5000"

  frontend:
    image: nieb/frontend
    ports:
      - "3000:80"
