FROM node:15
# WORKDIR /usr/src/app
WORKDIR /app

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install -production

COPY . .
RUN ls -l
ENV NODE_ENV=production

# EXPOSE 5000

CMD ["node", "simulatorAPI.js"]


