# This is a basic workflow to help you get started with Actions

name: Build and Push

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - Develop
  pull_request:
    branches: 
      - Develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_and_deploy_frontend:
    name: Build and Deploy frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: Frontend/Dockerfile
          context: ./Frontend
          push: true
          tags: minitwit/frontend:latest
          build-args: ACCESS_TOKEN_SECRET=${{secret.ACCESS_TOKEN_SECRET}}, DB_HOST=${{secret.DB_HOST}}, DB_USERNAME=${{secret.DB_USERNAME}}, DB_PASSWORD=${{secret.DB_PASSWORD}}, DB_NAME=${{secret.DB_NAME}}, DB_PORT=${{secret.DB_PORT}}
          
  build_and_deploy_api:
    name: Build and Deploy Api
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./API/Dockerfile
          context: ./API
          push: true
          tags: minitwit/api:latest
          build-args: ACCESS_TOKEN_SECRET=${{secret.ACCESS_TOKEN_SECRET}}, DB_HOST=${{secret.DB_HOST}}, DB_USERNAME=${{secret.DB_USERNAME}}, DB_PASSWORD=${{secret.DB_PASSWORD}}, DB_NAME=${{secret.DB_NAME}}, DB_PORT=${{secret.DB_PORT}}
          
  build_and_deploy_simulator:
    name: Build and Deploy Simulator
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./API/Dockerfile_simulator_api
          context: ./API
          push: true
          tags: minitwit/simulator:latest
          build-args: ACCESS_TOKEN_SECRET=${{secret.ACCESS_TOKEN_SECRET}}, DB_HOST=${{secret.DB_HOST}}, DB_USERNAME=${{secret.DB_USERNAME}}, DB_PASSWORD=${{secret.DB_PASSWORD}}, DB_NAME=${{secret.DB_NAME}}, DB_PORT=${{secret.DB_PORT}}

