# This is a basic workflow to help you get started with Actions

name: Build and Push

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - Develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_and_deploy_frontend:
    name: Build and Deploy frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: Frontend/Dockerfile-development
          context: ./Frontend
          push: true
          tags: minitwit/frontend_develop:latest
          
  build_and_deploy_api:
    name: Build and Deploy Api
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./API/Dockerfile-development
          context: ./API
          push: true
          tags: minitwit/api_develop:latest
          build-args: |
            ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}}
            DB_HOST=${{secrets.DB_HOST}}
            DB_USERNAME=${{secrets.DB_USERNAME}}
            DB_PASSWORD=${{secrets.DB_PASSWORD}}
            DB_NAME=${{secrets.DB_NAME_DEVELOP}}
            DB_PORT=${{secrets.DB_PORT}}

  build_and_deploy_simulator:
    name: Build and Deploy Simulator
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./API/Dockerfile_simulator_api
          context: ./API
          push: true
          tags: minitwit/simulator_develop:latest
          build-args: |
            ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}}
            DB_HOST=${{secrets.DB_HOST}}
            DB_USERNAME=${{secrets.DB_USERNAME}}
            DB_PASSWORD=${{secrets.DB_PASSWORD}}
            DB_NAME=${{secrets.DB_NAME_DEVELOP}}
            DB_PORT=${{secrets.DB_PORT}}

  update_docker_swarm_services:

    runs-on: ubuntu-latest
    needs: [build_and_deploy_frontend, build_and_deploy_api, build_and_deploy_simulator]
    
    steps:
    - uses: actions/checkout@v2

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_DEVELOP_HOST }}
        USERNAME: ${{ secrets.DROPLET_DEVELOP_USERNAME }}
        PORT: 22
        KEY: ${{ secrets.DROPLET_DEVELOP_SSHKEY }}
        script: docker service update --image index.docker.io/minitwit/simulator_develop minitwit_swarm_sim-api &&
                docker service update --image index.docker.io/minitwit/api_develop minitwit_swarm_api &&
                docker service update --image index.docker.io/minitwit/frontend_develop minitwit_swarm_frontend
