# This is a basic workflow to help you get started with Actions

name: ESLint

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: 
      - Develop
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  eslintAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: API/
        continue-on-error: false

  eslintFrontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: Frontend/
        continue-on-error: false
