name: Latex to PDF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report/main.tex

      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: build
        uses: github-actions-x/hugo@master
      - name: push
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'publish main.pdf'
          force-add: 'true'
          files: report/main.pdf
          name: Github Action
          email: hampuswadum@hotmail.com 
