name: Latex to PDF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report/main.tex

      - name: build
        uses: github-actions-x/hugo@master
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
          message: 'publish main.pdf'
          force: 'true'
          directory: ./report
          author_email: hampuswadum@hotmail.com 
