name: Update Docker Swarm Services

on:
  push:
    branches: 
      - docker-swarm

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_PRODUCTION_HOST }}
        USERNAME: ${{ secrets.DROPLET_PRODUCTION_USERNAME }}
        PORT: 22
        KEY: ${{ secrets.DROPLET_PRODUCTION_SSHKEY }}
        script: docker service update --image index.docker.io/minitwit/simulator minitwit_swarm_sim-api &&
                docker service update --image index.docker.io/minitwit/api minitwit_swarm_api &&
                docker service update --image index.docker.io/minitwit/frontend minitwit_swarm_frontend