name: Update Docker Swarm Services

on:
  push:
    branches: 
      - docker-swarm

  workflow_dispatch:

jobs:

  update_docker_swarm_services:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_DEVELOP_HOST }}
        USERNAME: ${{ secrets.DROPLET_DEVELOP_USERNAME }}
        PORT: 22
        KEY: ${{ secrets.DROPLET_DEVELOP_SSHKEY }}
        script: docker service update --image index.docker.io/minitwit/simulator_develop minitwit_swarm_sim-api &&
                docker service update --image index.docker.io/minitwit/api_develop minitwit_swarm_api &&
                docker service update --image index.docker.io/minitwit/frontend_develop minitwit_swarm_frontend